"""
src/publisher/publisher.py
─────────────────────────────────────────────────────────────────────────────
Auto Publisher Agent — Publishes videos to YouTube Shorts.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from tenacity import retry, stop_after_attempt, wait_exponential

from config.settings import settings
from src.core.exceptions import PublishingError
from src.utils.logger import get_logger
from src.utils.models import FinalVideo, NicheConfig, Platform, PublishResult

logger = get_logger("publisher")


class BasePublisher:
    """Base class for platform-specific publishers."""

    platform: Platform

    def publish(self, video: FinalVideo, niche: NicheConfig) -> PublishResult:
        raise NotImplementedError

    def _make_result(
        self,
        success: bool = False,
        post_id: str = "",
        post_url: str = "",
        error: str = "",
    ) -> PublishResult:
        return PublishResult(
            platform=self.platform,
            success=success,
            post_id=post_id,
            post_url=post_url,
            error=error,
            published_at=datetime.utcnow() if success else None,
        )


class YouTubePublisher(BasePublisher):
    """Publish to YouTube Shorts via YouTube Data API v3."""

    platform = Platform.YOUTUBE

    # Path to token.json generated by  scripts/youtube_oauth_setup.py
    TOKEN_FILE = Path(settings.project_root) / "token.json"

    def _load_credentials(self):
        """Load OAuth credentials from token.json, refreshing if expired."""
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials

        if not self.TOKEN_FILE.exists():
            raise PublishingError(
                "token.json not found. Run:  python setup_youtube_auth.py"
            )

        creds = Credentials.from_authorized_user_file(
            str(self.TOKEN_FILE),
            scopes=["https://www.googleapis.com/auth/youtube.upload"],
        )

        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                logger.info("youtube_token_refreshing")
                creds.refresh(Request())
                # Persist refreshed token
                with open(self.TOKEN_FILE, "w", encoding="utf-8") as f:
                    f.write(creds.to_json())
                logger.info("youtube_token_refreshed")
            else:
                raise PublishingError(
                    "token.json credentials are invalid or expired. "
                    "Delete token.json and re-run:  python setup_youtube_auth.py"
                )

        return creds

    def upload_video_file(
        self,
        video_path: Path,
        *,
        title: str,
        description: str = "",
        tags: list[str] | None = None,
        category_id: str = "28",
        privacy_status: str = "public",
    ) -> dict:
        """
        Upload a local video file and return the raw YouTube Data API v3 response dict.
        Used for one-off test uploads; does not apply retry (caller logs success/failure).
        """
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        path = Path(video_path).resolve()
        if not path.is_file():
            raise PublishingError(f"Video file not found: {path}")

        creds = self._load_credentials()
        youtube = build("youtube", "v3", credentials=creds)
        tag_list = (tags or [])[:30]

        body = {
            "snippet": {
                "title": title[:100],
                "description": description,
                "tags": tag_list,
                "categoryId": category_id,
            },
            "status": {
                "privacyStatus": privacy_status,
                "selfDeclaredMadeForKids": False,
                "madeForKids": False,
            },
        }

        media = MediaFileUpload(
            str(path),
            mimetype="video/mp4",
            resumable=True,
            chunksize=10 * 1024 * 1024,
        )

        request = youtube.videos().insert(
            part="snippet,status",
            body=body,
            media_body=media,
        )
        return request.execute()

    @retry(
        stop=stop_after_attempt(2),
        wait=wait_exponential(multiplier=2, min=5, max=30),
    )
    def publish(self, video: FinalVideo, niche: NicheConfig) -> PublishResult:
        logger.info("publishing_youtube", title=video.title)

        try:
            from googleapiclient.discovery import build
            from googleapiclient.http import MediaFileUpload

            creds = self._load_credentials()
            youtube = build("youtube", "v3", credentials=creds)

            body = {
                "snippet": {
                    "title": video.title[:100],
                    "description": video.description,
                    "tags": video.tags[:30],
                    "categoryId": niche.youtube_category_id,
                },
                "status": {
                    "privacyStatus": "public",
                    "selfDeclaredMadeForKids": False,
                    "madeForKids": False,
                },
            }

            media = MediaFileUpload(
                str(video.video_path),
                mimetype="video/mp4",
                resumable=True,
                chunksize=10 * 1024 * 1024,
            )

            request = youtube.videos().insert(
                part="snippet,status",
                body=body,
                media_body=media,
            )

            response = request.execute()
            video_id = response.get("id", "")

            logger.info("youtube_published", video_id=video_id)
            return self._make_result(
                success=True,
                post_id=video_id,
                post_url=f"https://youtube.com/shorts/{video_id}",
            )

        except PublishingError:
            raise
        except Exception as e:
            logger.error("youtube_publish_failed", error=str(e))
            return self._make_result(error=str(e))


class AutoPublisher:
    """Orchestrates publishing to YouTube."""

    def __init__(self) -> None:
        self._publishers: dict[Platform, BasePublisher] = {
            Platform.YOUTUBE: YouTubePublisher(),
        }

    def publish_all(
        self,
        video: FinalVideo,
        niche: NicheConfig,
        platforms: list[Platform] | None = None,
        dry_run: bool = False,
    ) -> list[PublishResult]:
        """Publish video to YouTube."""
        target_platforms = platforms or list(self._publishers.keys())
        results: list[PublishResult] = []

        logger.info(
            "auto_publish_start",
            title=video.title,
            platforms=[p.value for p in target_platforms],
            dry_run=dry_run,
        )

        for platform in target_platforms:
            if dry_run:
                logger.info("dry_run_skip_publish", platform=platform.value)
                results.append(
                    PublishResult(
                        platform=platform,
                        success=True,
                        post_id="dry-run",
                        post_url="",
                        published_at=datetime.utcnow(),
                    )
                )
                continue

            publisher = self._publishers.get(platform)
            if not publisher:
                logger.warning("unknown_platform", platform=platform.value)
                continue

            try:
                result = publisher.publish(video, niche)
                results.append(result)
                if result.success:
                    logger.info(
                        "published",
                        platform=platform.value,
                        post_url=result.post_url,
                    )
                else:
                    logger.warning(
                        "publish_failed",
                        platform=platform.value,
                        error=result.error,
                    )
            except Exception as e:
                logger.error(
                    "publish_error",
                    platform=platform.value,
                    error=str(e),
                )
                results.append(
                    PublishResult(
                        platform=platform,
                        success=False,
                        error=str(e),
                    )
                )

        published = sum(1 for r in results if r.success)
        logger.info(
            "auto_publish_complete",
            total=len(results),
            published=published,
            failed=len(results) - published,
        )
        return results
